#!/usr/bin/python
# -*- tab-width: 4; use-tabs: 1; coding: utf-8 -*-
# vim:tabstop=4:noexpandtab:
"""
Feeds a single line into CouchDB.
"""

class Line(object):
	when = 0
	channel = ""
	sender = ""
	event = ""

class PRIVMSG(Line):
	event = "PRIVMSG"
	text = ""

class Action(PRIVMSG):
	what = ""

class JOIN(Line):
	event = "JOIN"

class PART(Line):
	event = "PART"
	text = ""

class QUIT(Line):
	event = "QUIT"
	text = ""

class KICK(Line):
	event = "KICK"
	target = ""
	text = ""

class MODE(Line):
	event = "MODE"
	target = ""
	mask = ""

class TOPIC(Line):
	event = "TOPIC"
	text = ""

class NOTICE(Line):
	event = "NOTICE"
	text = ""

class NICK(Line):
	event = "NICK"
	newnick = ""
