#!/usr/bin/python
# -*- tab-width: 4; use-tabs: 1; coding: utf-8 -*-
# vim:tabstop=4:noexpandtab:
"""
Sets up the CouchDB server.
"""
import os, warnings
from couchdb.client import Server
from tisc import Tisc

TISC = Tisc()
collection = TISC.option('collection')

try:
	Server().create(collection)
except:
	pass

for view, _ in TISC.views():
	print "View:", view
	
	design = TISC.couch().get("_design/%s" % view, {
		"language": "python",
		"views" : {},
	})
	for section, sectionpath in TISC.sections(view):
		print "Section:", section
		mappath = os.path.join(sectionpath, 'map.py')
		reducepath = os.path.join(sectionpath, 'reduce.py')
		
		design['views'][section] = {
			"map": open(mappath).read(),
		}
		if os.path.exists(reducepath):
			design['views'][section]["reduce"] = open(reducepath).read()
	
	TISC.couch()["_design/%s" % view] = design

