#!/usr/bin/python
# -*- tab-width: 4; use-tabs: 1; coding: utf-8 -*-
# vim:tabstop=4:noexpandtab:
"""
Sets up the CouchDB server.
"""
import os, warnings
from couchdb.client import Server
from tisc import Tisc

mycouch = Server()

try:
	mycouch.delete('tisc')
except:
	pass
mycouch.create('tisc')
TISC = Tisc()

for page in TISC.pages():
	print "Page:", page
	
	views = {}
	for section in TISC.sections(page):
		sectionpath = os.path.join(TISC.root, page, section)
		
		print "Section:", section
		mappath = os.path.join(sectionpath, 'map.py')
		reducepath = os.path.join(sectionpath, 'reduce.py')
		
		views[section] = {
			"map": open(mappath).read(),
		}
		if os.path.exists(reducepath):
			views[section]["reduce"] = open(reducepath).read()
	
	mycouch['tisc']["_design/%s" % page] = {
		"_id": "_design/%s" % page,
		"language": "python",
		"views" : views,
	}
	

