#!/usr/bin/python
# -*- tab-width: 4; use-tabs: 1; coding: utf-8 -*-
# vim:tabstop=4:noexpandtab:
"""
Downloads all the logs from online and feeds them into CouchDB.
"""
import os

dates = []
for month in range(4, 12):
	for day in range(1, 32):
		date = {'year': 2011, 'month': month, 'day': day}
		dates.append("%(year)i-%(month)02i-%(day)02i" % date)

os.execl('./feed-tgglog', './feed-tgglog', *dates)
